spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      default-view-inclusion: true
  datasource:
    platform: mysql
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anzplatform?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Minh7891@
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379

logging:
  level:
    ROOT: INFO
    #org.hibernate: ERROR
    #org.springframework.web: DEBUG
  com.anz.platform: DEBUG

server:
  servlet:
    context-path: /api/anzplatform/v1
  port: 8080

application:
  name: anz-platform
  env: local
