spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      default-view-inclusion: true
  datasource:
    platform: hsql
    initialization-mode: never
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:test;sql.syntax_pgs=true
    username: sa
    password: ""
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.HSQLDialect
  redis:
    host: localhost
    port: 6379

logging:
  level:
    ROOT: INFO
    #org.hibernate: ERROR
    #org.springframework.web: DEBUG
  com.anz.platform: DEBUG

server:
  servlet:
    context-path: /api/anzplatform/v1
  port: 8080

application:
  name: anz-platform
  env: dev
